### ISSUE TITLE
Case Studies Section

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#51]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20887673/a7ff201c-bac9-11e6-98e8-61fa7bfc7c8d.png)

Everything you need:
https://drive.google.com/drive/folders/0B5DWXoUiIyAJbU5yR0gzMlliQlk?usp=sharing

**Comment by marianovegab** [comment]
Hello guys @mjbarnes88 @luigicr18  
Please take a look at this notes.
<img width="865" alt="screenshot at dec 12 15-44-20" src="https://cloud.githubusercontent.com/assets/8145017/21118296/e102c706-c082-11e6-996d-3f19b64327f2.png">
<img width="708" alt="screenshot at dec 12 15-50-00" src="https://cloud.githubusercontent.com/assets/8145017/21118299/e3810ae2-c082-11e6-88e4-eb954628248b.png">

Thanks

**Comment by marianovegab** [comment]
Hello
All notes fixed now 
<img width="1677" alt="screen shot 2016-12-15 at 12 02 40 pm" src="https://cloud.githubusercontent.com/assets/8145017/21235919/79032964-c2be-11e6-96cf-19d441e60045.png">
Thanks

**Comment by mjbarnes88** [comment]
Needs greater margin between and a max width for larger screen sizes

#happyClients img {
    padding: 0 3em;
    width: 28%;
    max-width: 446px;
}

**Comment by mjbarnes88** [comment]
Please use
background-size: cover;

for each of the images in this section. On larger screens, the images tile.
![image](https://cloud.githubusercontent.com/assets/23315246/21265717/a8fd16ea-c370-11e6-8b2d-30e1f1d0e050.png)

![image](https://cloud.githubusercontent.com/assets/23315246/21265740/c213efa0-c370-11e6-946e-3ee0b91bbe18.png)

**Comment by mjbarnes88** [comment]
![image](https://cloud.githubusercontent.com/assets/23315246/21297480/51f50ffc-c54f-11e6-8ba6-077e6863ab2d.png)

Images are bigger than their natural size on larger screens. Use max width and increase padding

#happyClients img {
    padding: 0px 3em;
    width: 28%;
    max-width: 397px;
}

![image](https://cloud.githubusercontent.com/assets/23315246/21297479/4165b524-c54f-11e6-9aad-6ef9e4171ff5.png)

**Comment by mjbarnes88** [comment]
You missed the: padding: 0 3em;

#happyClients img {
padding: 0px 3em;
width: 28%;
max-width: 397px;
}

**Comment by mjbarnes88** [comment]
Still seeing the wrong padding
![image](https://cloud.githubusercontent.com/assets/23315246/21372982/0672bac0-c6e9-11e6-92b3-50e7746e1197.png)
